name: Docker Image CI

# Leave out specific branches so this same workflow can be used on any branch
on: [ push, pull_request ]

jobs:

  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the commit that triggered the workflow
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache --tag unidata/ldm-docker:latest .
    - name: Run the container
      run: |
        docker run --name ldm \
        -e LDM_USER_ID=$(id -u) \
        -e LDM_GROUP_ID=$(getent group $USER | cut -d : -f3) \
        -v $(pwd)/etc:/home/ldm/etc \
        -v $(pwd)/data:/home/ldm/var/data \
        -v $(pwd)/queues:/home/ldm/var/queues \
        -v $(pwd)/logs:/home/ldm/var/logs \
        -d \
        -p 388:388 \
        unidata/ldm-docker:latest
    - run: docker exec ldm ldmadmin config
